#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE=make

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi
rm -rf work/lib
cp -pPR lib work/       # OSX dos not support cp -a
opp_test gen $OPT -v $TESTFILES || exit 1
echo

# Output directory
PROJECT_OUTPUT_DIR=out
CONFIGNAME=gcc-debug
PROJECTRELATIVE_PATH=src
O=../../../$PROJECT_OUTPUT_DIR/$CONFIGNAME/$PROJECTRELATIVE_PATH

# Object files for HomaTransport .cc and .msg files
OBJS=\
"$O/application/MsgSizeDistributions.o "\
"$O/application/WorkloadSynthesizer.o "\
"$O/common/Lagger.o "\
"$O/common/Util.o "\
"$O/transport/HomaPkt.o "\
"$O/transport/HomaTransport.o "\
"$O/transport/PriorityResolver.o "\
"$O/transport/PseudoIdealPriorityTransport.o "\
"$O/transport/TrafficPacer.o "\
"$O/transport/UnschedByteAllocator.o "\
"$O/transport/WorkloadEstimator.o "\
"$O/application/AppMessage_m.o "\
"$O/transport/HomaPkt_m.o "



(cd work; opp_makemake -f --deep -L../../../../inet/src -lINET -P .  -I../../../src -I./lib -I../../../../inet/src $OBJS; $MAKE) || exit 1
echo
opp_test run $OPT -v $TESTFILES || exit 1
echo
echo Results can be found in ./work
