#!/usr/bin/Rscript
library(reshape2)
library(ggplot2)
library(gridExtra)
library(plyr)

# Plots the stretch vs. unsched bytes from text data files generated by PlotDigeter.py script
wastedBw <- read.table("wastedBw.txt", na.strings = "NA",
    col.names=c('workload', 'redundancyFactor', 'loadFactor', 'nominalLoadFactor', 'wastedBw', 'activeWastedBw'),
    header=TRUE)
wastedBw$redundancyFactor <- factor(wastedBw$redundancyFactor)
i <- 0
plotList <- list()
textSize = 13
yLab = 'Receiver Wasted Bandwidth(%)'
xLab = 'Average Load Factor(%)'
workloads <- c('FACEBOOK_KEY_VALUE', 'GOOGLE_SEARCH_RPC', 'FABRICATED_HEAVY_MIDDLE', 'GOOGLE_ALL_RPC','FACEBOOK_HADOOP_ALL')
for (workload in workloads) {
    i <- i+1
    plotTitle = sprintf("Workload: %s", workload)
    plotList[[i]] <- ggplot(wastedBw[wastedBw$workload==workload,], aes(x=loadFactor, y=wastedBw, colour=redundancyFactor)) +
        geom_line(size = 2, alpha = 1/2) +
        theme(text = element_text(size=textSize, face="bold"), legend.position="top",
            strip.text.x = element_text(size = textSize), strip.text.y = element_text(size = textSize),
            plot.title = element_text(size = textSize)) +
        coord_cartesian(ylim=c(0,100), xlim=c(0,100)) +
        labs(title = plotTitle, x = xLab, y = yLab)
}

pdf("plots/wastedBW.pdf", width=15, height=10)
args.list <- c(plotList, list(ncol=3))
do.call(grid.arrange, args.list)
dev.off()

