#!/usr/bin/Rscript
library(reshape2)
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)

# Plots the stretch vs. unsched bytes from text data files generated by PlotDigeter.py script
stretchVsSize <- read.table("stretchVsUnschedPrioMode.txt", na.strings = "NA",
    col.names=c('TransportType', 'LoadFactor', 'UnschedPrioCutoff', 'ExponentIncFactor',
        'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'BytesPercent',
        'UnschedBytes', 'MeanStretch', 'MedianStretch', 'TailStretch'),
    header=TRUE)
stretchVsSize$LoadFactor <- factor(stretchVsSize$LoadFactor)
stretchVsSize$TransportType <- factor(stretchVsSize$TransportType)

meanStretchVsSize <- subset(stretchVsSize,
    !is.na(MeanStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
    select=c('TransportType', 'LoadFactor', 'WorkLoad', 'UnschedPrioCutoff', 'ExponentIncFactor',
    'MsgSizeRange', 'SizeCntPercent', 'BytesPercent', 'UnschedBytes', 'MeanStretch'))
meanStretchVsSize <- ddply(meanStretchVsSize, .(TransportType, LoadFactor, WorkLoad, UnschedBytes, UnschedPrioCutoff, ExponentIncFactor), transform,
    SizeCumPercent = round(cumsum(SizeCntPercent), 2), BytesCumPercent = round(cumsum(BytesPercent), 2))
meanStretchVsSize$MsgSizeRange <- as.numeric(as.character(meanStretchVsSize$MsgSizeRange))

medianStretchVsSize <- subset(stretchVsSize,
    !is.na(MedianStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
    select=c('TransportType', 'LoadFactor', 'WorkLoad', 'UnschedPrioCutoff', 'ExponentIncFactor',
    'MsgSizeRange', 'SizeCntPercent', 'BytesPercent', 'UnschedBytes', 'MedianStretch'))
medianStretchVsSize <- ddply(medianStretchVsSize, .(TransportType, LoadFactor, WorkLoad, UnschedBytes, UnschedPrioCutoff, ExponentIncFactor), transform,
    SizeCumPercent = round(cumsum(SizeCntPercent), 2), BytesCumPercent = round(cumsum(BytesPercent), 2))
medianStretchVsSize$MsgSizeRange <- as.numeric(as.character(medianStretchVsSize$MsgSizeRange))

tailStretchVsSize <- subset(stretchVsSize,
    !is.na(TailStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
    select=c('TransportType', 'LoadFactor', 'WorkLoad', 'UnschedPrioCutoff', 'ExponentIncFactor',
    'MsgSizeRange', 'SizeCntPercent', 'BytesPercent', 'UnschedBytes', 'TailStretch'))
tailStretchVsSize <- ddply(tailStretchVsSize, .(TransportType, LoadFactor, WorkLoad, UnschedBytes, UnschedPrioCutoff, ExponentIncFactor), transform,
    SizeCumPercent = round(cumsum(SizeCntPercent), 2), BytesCumPercent = round(cumsum(BytesPercent), 2))
tailStretchVsSize$MsgSizeRange <- as.numeric(as.character(tailStretchVsSize$MsgSizeRange))

textSize <- 35 
titleSize <- 35
yLimit <- 10
workloads <- c(levels(tailStretchVsSize$WorkLoad)[2],
    levels(tailStretchVsSize$WorkLoad)[3], levels(tailStretchVsSize$WorkLoad)[1])

####################Tail Plots###############################
exponents <- c()
exponentFacs <- unique(tailStretchVsSize$ExponentIncFactor)
for (val in exponentFacs) {
    exponents <- c(exponents, eval(parse(text=as.character(val))))
}

aggregateStats <- data.frame(Workload=c(), PrioMode=c(), SizeRange=c(), Exponent=c(), AggrTail=c())
for (rho in unique(tailStretchVsSize$LoadFactor)) {
    for (workload in workloads) {
        i <- 0
        tailStretchPlot = list()

        for (prioMode in unique(tailStretchVsSize$UnschedPrioCutoff)) {
            for (exponentIncFac in exponentFacs[order(exponents)]) {
                # Use CDF as the x axis
                i <- i+1
                tmp <- subset(tailStretchVsSize, WorkLoad==workload & LoadFactor==rho & ExponentIncFactor==exponentIncFac & UnschedPrioCutoff == prioMode,
                    select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'SizeCumPercent',
                    'TransportType', 'TailStretch', 'UnschedBytes'))

                plotTitle = sprintf("Workload: %s, PrioMode: %s, Exponent: %s", workload, prioMode, exponentIncFac)
                yLab = 'TailStretch (Log Scale)\n'
                xLab <- 'Message Sizes (Bytes)'

                # You might ask why I'm using "x=SizeCumPercent-SizeCntPercent/200" in the plot? The reason is that ggplot geom_bar is so
                # dumb and I was not able to shift the bars to the write while setting the width of each bar to be equal to it's size
                # probability. So I ended up manaully shift the bars to the the left for half of the probability and setting the width
                # equal to the probability
                tailStretchPlot[[i]] <- ggplot() +
                    geom_step(data=tmp, aes(x=SizeCumPercent-SizeCntPercent/2, y=TailStretch, width=SizeCntPercent, colour=TransportType), size=4)

                plotTitle <- paste(append(unlist(strsplit(plotTitle, split='')), '\n', as.integer(nchar(plotTitle)/2)), sep='', collapse='')
                xIntervals <- findInterval(c(0)+seq(2,102,10), tmp[tmp$TransportType=='homa',]$SizeCumPercent)
                tailStretchPlot[[i]] <- tailStretchPlot[[i]] +
                    theme(text = element_text(size=1.5*textSize), axis.text = element_text(size=1.3*textSize),
                        axis.text.x = element_text(angle=75, vjust=0.5), strip.text = element_text(size = textSize),
                        plot.title = element_text(size = 1.2*titleSize, color='darkblue'), plot.margin=unit(c(2,2,2.5,2.2),"cm"),
                        legend.position = c(0.1, 0.85), legend.text = element_text(size=1.5*textSize)) +
                    scale_x_continuous(limits = c(0,101), breaks = tmp[xIntervals,]$SizeCumPercent, labels=tmp[xIntervals,]$MsgSizeRange, expand = c(0, 0)) +
                    scale_y_log10(breaks=c(1,2,3,4,5,10,15)) +
                    coord_cartesian(ylim=c(1, yLimit)) +
                    labs(title = plotTitle, y = yLab, x = xLab)


                ## find aggreage stretch stats for ranges of message sizes
                rollingSum <- 0
                sumProb <- 0
                weightedTail <- tmp$TailStretch * tmp$SizeCntPercent / 100
                msgSizeBins = c(1442, 9328, 46640, 1e10)
                j <- 1
                k <- 1
                while (j<=nrow(tmp)){
                    sizeRange = tmp$MsgSizeRange[j]
                    prob <- tmp$SizeCntPercent[j] / 100
                    if (sizeRange >= msgSizeBins[k]) {
                        aggregateStats <- rbind(aggregateStats, data.frame(Workload=c(workload), PrioMode=c(prioMode), SizeRange=c(msgSizeBins[k]),
                            Exponent=c(round(eval(parse(text=exponentIncFac)),2)), AggrTail=c(rollingSum/sumProb)))
                        rollingSum <- 0
                        sumProb <- 0
                        k <- k+1
                    }
                    rollingSum <- rollingSum + weightedTail[j]
                    sumProb <- sumProb + prob

                    if (j == nrow(tmp)) {
                        aggregateStats <- rbind(aggregateStats, data.frame(Workload=c(workload), PrioMode=c(prioMode), SizeRange=c(msgSizeBins[k]),
                            Exponent=c(round(eval(parse(text=exponentIncFac)),2)), AggrTail=c(rollingSum/sumProb)))

                    }
                    j <- j+1
                } 
            }
        }
        pdf(sprintf("plots/unschedPrioMode/TailStretchVsTransport_rho%s_%s.pdf", rho, workload),
            width=200,
            height=40)
        args.list <- c(tailStretchPlot, list(ncol=7))
        do.call(grid.arrange, args.list)
        dev.off()
    }
}
aggregateStatsReshaped <- dcast(aggregateStats, Workload+PrioMode+SizeRange~Exponent)
for (workload in workloads) {
    tmp <- subset(aggregateStatsReshaped, Workload==workload, select=-Workload)
    pdf<-pdf(sprintf("plots/unschedPrioMode/TailStretchVsTransport_AggrStats_%s.pdf", workload), width=12, height=6)
    grid.table(tmp)
    dev.off()

}

####################Median Plots###############################

exponents <- c()
exponentFacs <- unique(medianStretchVsSize$ExponentIncFactor)
for (val in exponentFacs) {
    exponents <- c(exponents, eval(parse(text=as.character(val))))
}

aggregateStats <- data.frame(Workload=c(), PrioMode=c(), SizeRange=c(), Exponent=c(), AggrMedian=c())
for (rho in unique(medianStretchVsSize$LoadFactor)) {
    for (workload in workloads) {
        i <- 0
        medianStretchPlot = list()

        for (prioMode in unique(medianStretchVsSize$UnschedPrioCutoff)) {
            for (exponentIncFac in exponentFacs[order(exponents)]) {
                # Use CDF as the x axis
                i <- i+1
                tmp <- subset(medianStretchVsSize, WorkLoad==workload & LoadFactor==rho & ExponentIncFactor==exponentIncFac & UnschedPrioCutoff == prioMode,
                    select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'SizeCumPercent',
                    'TransportType', 'MedianStretch', 'UnschedBytes'))

                plotTitle = sprintf("Workload: %s, PrioMode: %s, Exponent: %s", workload, prioMode, exponentIncFac)
                yLab = 'MedianStretch (Log Scale)\n'
                xLab <- 'Message Sizes (Bytes)'

                # You might ask why I'm using "x=SizeCumPercent-SizeCntPercent/200" in the plot? The reason is that ggplot geom_bar is so
                # dumb and I was not able to shift the bars to the write while setting the width of each bar to be equal to it's size
                # probability. So I ended up manaully shift the bars to the the left for half of the probability and setting the width
                # equal to the probability
                medianStretchPlot[[i]] <- ggplot() +
                    geom_step(data=tmp, aes(x=SizeCumPercent-SizeCntPercent/2, y=MedianStretch, width=SizeCntPercent, colour=TransportType), size=4)

                plotTitle <- paste(append(unlist(strsplit(plotTitle, split='')), '\n', as.integer(nchar(plotTitle)/2)), sep='', collapse='')
                xIntervals <- findInterval(c(0)+seq(2,102,10), tmp[tmp$TransportType=='homa',]$SizeCumPercent)
                medianStretchPlot[[i]] <- medianStretchPlot[[i]] +
                    theme(text = element_text(size=1.5*textSize), axis.text = element_text(size=1.3*textSize),
                        axis.text.x = element_text(angle=75, vjust=0.5), strip.text = element_text(size = textSize),
                        plot.title = element_text(size = 1.2*titleSize, color='darkblue'), plot.margin=unit(c(2,2,2.5,2.2),"cm"),
                        legend.position = c(0.1, 0.85), legend.text = element_text(size=1.5*textSize)) +
                    scale_x_continuous(limits = c(0,101), breaks = tmp[xIntervals,]$SizeCumPercent, labels=tmp[xIntervals,]$MsgSizeRange, expand = c(0, 0)) +
                    scale_y_log10(breaks=c(1,2,3,4,5,10,15)) +
                    coord_cartesian(ylim=c(1, yLimit)) +
                    labs(title = plotTitle, y = yLab, x = xLab)

                ## find aggreage stretch stats for ranges of message sizes
                rollingSum <- 0
                sumProb <- 0
                weightedMedian <- tmp$MedianStretch * tmp$SizeCntPercent / 100
                msgSizeBins = c(1442, 9328, 46640, 1e10)
                j <- 1
                k <- 1
                while (j<=nrow(tmp)){
                    sizeRange = tmp$MsgSizeRange[j]
                    prob <- tmp$SizeCntPercent[j] / 100
                    if (sizeRange >= msgSizeBins[k]) {
                        aggregateStats <- rbind(aggregateStats, data.frame(Workload=c(workload), PrioMode=c(prioMode), SizeRange=c(msgSizeBins[k]),
                            Exponent=c(round(eval(parse(text=exponentIncFac)),2)), AggrMedian=c(rollingSum/sumProb)))
                        rollingSum <- 0
                        sumProb <- 0
                        k <- k+1
                    }
                    rollingSum <- rollingSum + weightedMedian[j]
                    sumProb <- sumProb + prob

                    if (j == nrow(tmp)) {
                        aggregateStats <- rbind(aggregateStats, data.frame(Workload=c(workload), PrioMode=c(prioMode), SizeRange=c(msgSizeBins[k]),
                            Exponent=c(round(eval(parse(text=exponentIncFac)),2)), AggrMedian=c(rollingSum/sumProb)))

                    }
                    j <- j+1
                } 
            }
        }
        pdf(sprintf("plots/unschedPrioMode/MedianStretchVsTransport_rho%s_%s.pdf", rho, workload),
            width=200,
            height=40)
        args.list <- c(medianStretchPlot, list(ncol=7))
        do.call(grid.arrange, args.list)
        dev.off()
    }
}
aggregateStatsReshaped <- dcast(aggregateStats, Workload+PrioMode+SizeRange~Exponent)
for (workload in workloads) {
    tmp <- subset(aggregateStatsReshaped, Workload==workload, select=-Workload)
    pdf<-pdf(sprintf("plots/unschedPrioMode/MedianStretchVsTransport_AggrStats_%s.pdf", workload), width=12, height=6)
    grid.table(tmp)
    dev.off()

}


####################Mean Plots###############################
exponents <- c()
exponentFacs <- unique(meanStretchVsSize$ExponentIncFactor)
for (val in exponentFacs) {
    exponents <- c(exponents, eval(parse(text=as.character(val))))
}

aggregateStats <- data.frame(Workload=c(), PrioMode=c(), SizeRange=c(), Exponent=c(), AggrMean=c())
for (rho in unique(meanStretchVsSize$LoadFactor)) {
    for (workload in workloads) {
        i <- 0
        meanStretchPlot = list()

        for (prioMode in unique(meanStretchVsSize$UnschedPrioCutoff)) {
            for (exponentIncFac in exponentFacs[order(exponents)]) {
                # Use CDF as the x axis
                i <- i+1
                tmp <- subset(meanStretchVsSize, WorkLoad==workload & LoadFactor==rho & ExponentIncFactor==exponentIncFac & UnschedPrioCutoff == prioMode,
                    select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'SizeCumPercent',
                    'TransportType', 'MeanStretch', 'UnschedBytes'))

                plotTitle = sprintf("Workload: %s, PrioMode: %s, Exponent: %s", workload, prioMode, exponentIncFac)
                yLab = 'MeanStretch (Log Scale)\n'
                xLab <- 'Message Sizes (Bytes)'

                # You might ask why I'm using "x=SizeCumPercent-SizeCntPercent/200" in the plot? The reason is that ggplot geom_bar is so
                # dumb and I was not able to shift the bars to the write while setting the width of each bar to be equal to it's size
                # probability. So I ended up manaully shift the bars to the the left for half of the probability and setting the width
                # equal to the probability
                meanStretchPlot[[i]] <- ggplot() +
                    geom_step(data=tmp, aes(x=SizeCumPercent-SizeCntPercent/2, y=MeanStretch, width=SizeCntPercent, colour=TransportType), size=4)

                plotTitle <- paste(append(unlist(strsplit(plotTitle, split='')), '\n', as.integer(nchar(plotTitle)/2)), sep='', collapse='')
                xIntervals <- findInterval(c(0)+seq(2,102,10), tmp[tmp$TransportType=='homa',]$SizeCumPercent)
                meanStretchPlot[[i]] <- meanStretchPlot[[i]] +
                    theme(text = element_text(size=1.5*textSize), axis.text = element_text(size=1.3*textSize),
                        axis.text.x = element_text(angle=75, vjust=0.5), strip.text = element_text(size = textSize),
                        plot.title = element_text(size = 1.2*titleSize, color='darkblue'), plot.margin=unit(c(2,2,2.5,2.2),"cm"),
                        legend.position = c(0.1, 0.85), legend.text = element_text(size=1.5*textSize)) +
                    scale_x_continuous(limits = c(0,101), breaks = tmp[xIntervals,]$SizeCumPercent, labels=tmp[xIntervals,]$MsgSizeRange, expand = c(0, 0)) +
                    scale_y_log10(breaks=c(1,2,3,4,5,10,15)) +
                    coord_cartesian(ylim=c(1, yLimit)) +
                    labs(title = plotTitle, y = yLab, x = xLab)

                ## find aggreage stretch stats for ranges of message sizes
                rollingSum <- 0
                sumProb <- 0
                weightedMean <- tmp$MeanStretch * tmp$SizeCntPercent / 100
                msgSizeBins = c(1442, 9328, 46640, 1e10)
                j <- 1
                k <- 1
                while (j<=nrow(tmp)){
                    sizeRange = tmp$MsgSizeRange[j]
                    prob <- tmp$SizeCntPercent[j] / 100
                    if (sizeRange >= msgSizeBins[k]) {
                        aggregateStats <- rbind(aggregateStats, data.frame(Workload=c(workload), PrioMode=c(prioMode), SizeRange=c(msgSizeBins[k]),
                            Exponent=c(round(eval(parse(text=exponentIncFac)),2)), AggrMean=c(rollingSum/sumProb)))
                        rollingSum <- 0
                        sumProb <- 0
                        k <- k+1
                    }
                    rollingSum <- rollingSum + weightedMean[j]
                    sumProb <- sumProb + prob

                    if (j == nrow(tmp)) {
                        aggregateStats <- rbind(aggregateStats, data.frame(Workload=c(workload), PrioMode=c(prioMode), SizeRange=c(msgSizeBins[k]),
                            Exponent=c(round(eval(parse(text=exponentIncFac)),2)), AggrMean=c(rollingSum/sumProb)))

                    }
                    j <- j+1
                } 
            }
        }
        pdf(sprintf("plots/unschedPrioMode/MeanStretchVsTransport_rho%s_%s.pdf", rho, workload),
            width=200,
            height=40)
        args.list <- c(meanStretchPlot, list(ncol=7))
        do.call(grid.arrange, args.list)
        dev.off()
    }
}
aggregateStatsReshaped <- dcast(aggregateStats, Workload+PrioMode+SizeRange~Exponent)
for (workload in workloads) {
    tmp <- subset(aggregateStatsReshaped, Workload==workload, select=-Workload)
    pdf<-pdf(sprintf("plots/unschedPrioMode/MeanStretchVsTransport_AggrStats_%s.pdf", workload), width=12, height=6)
    grid.table(tmp)
    dev.off()

}
