#!/usr/bin/Rscript
library(reshape2)
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)

# Plots the stretch vs. unsched bytes from text data files generated by
# PlotDigeter.py script
stretchVsSize <- read.table("stretchVsSchedUnschedPrioCutoff.txt",
    na.strings = "NA",
    col.names=c('TransportType', 'LoadFactor', 'PrioLevels', 'SchedPrios',
    'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'BytesPercent',
    'UnschedBytes', 'MeanStretch', 'MedianStretch', 'TailStretch'),
    header=TRUE)

stretchVsSize$TransportType <- factor(stretchVsSize$TransportType)
avgStretchVsSize <- subset(stretchVsSize,
    !is.na(MeanStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
    select=c('TransportType', 'LoadFactor', 'PrioLevels', 'SchedPrios',
    'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'BytesPercent',
    'UnschedBytes', 'MeanStretch'))

avgStretchVsSize <- ddply(avgStretchVsSize,
    .(TransportType, LoadFactor, WorkLoad, UnschedBytes, SchedPrios,
    PrioLevels), transform, SizeCumPercent = round(cumsum(SizeCntPercent), 2),
    BytesCumPercent = round(cumsum(BytesPercent), 2))

avgStretchVsSize$MsgSizeRange <- as.numeric(as.character(
    avgStretchVsSize$MsgSizeRange))

medianStretchVsSize <- subset(stretchVsSize,
    !is.na(MedianStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
    select=c('TransportType', 'LoadFactor', 'PrioLevels', 'SchedPrios',
    'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'BytesPercent',
    'UnschedBytes', 'MedianStretch'))

medianStretchVsSize <- ddply(medianStretchVsSize,
    .(TransportType, LoadFactor, WorkLoad, UnschedBytes, SchedPrios,
    PrioLevels), transform, SizeCumPercent = round(cumsum(SizeCntPercent), 2),
    BytesCumPercent = round(cumsum(BytesPercent), 2))

medianStretchVsSize$MsgSizeRange <- as.numeric(
    as.character(medianStretchVsSize$MsgSizeRange))

tailStretchVsSize <- subset(stretchVsSize,
    !is.na(TailStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
    select=c('TransportType', 'LoadFactor', 'PrioLevels', 'SchedPrios',
    'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'BytesPercent',
    'UnschedBytes', 'TailStretch'))

tailStretchVsSize <- ddply(tailStretchVsSize,
    .(TransportType, LoadFactor, WorkLoad, UnschedBytes, SchedPrios,
    PrioLevels), transform, SizeCumPercent = round(cumsum(SizeCntPercent), 2),
    BytesCumPercent = round(cumsum(BytesPercent), 2))

tailStretchVsSize$MsgSizeRange <- as.numeric(
    as.character(tailStretchVsSize$MsgSizeRange))

textSize <- 55 
titleSize <- 55 
yLimit <- 15
workloads <- c(
    levels(avgStretchVsSize$WorkLoad)[3], levels(avgStretchVsSize$WorkLoad)[5],
    levels(avgStretchVsSize$WorkLoad)[1], levels(avgStretchVsSize$WorkLoad)[4],
    levels(avgStretchVsSize$WorkLoad)[2])
workloads <- workloads[!is.na(workloads)]
rhos = c(0.8)
#rhos = unique(tailStretchVsSize$LoadFactor)
prioLevels = c(8)
#prioLevels = unique(tailStretchVsSize$PrioLevels)

for (rho in rhos) {
    i <- 0
    tailStretchPlot = list()
    for (prioLevel in prioLevels) {
        for (workload in workloads) {
            # Use CDF as the x axis
            tmp <- subset(tailStretchVsSize, WorkLoad==workload &
                PrioLevels==prioLevel & LoadFactor==rho,
                select=c('MsgSizeRange', 'SizeCntPercent', 'SchedPrios',
                'SizeCumPercent', 'TailStretch'))
            tmp$SchedPrios <- factor(tmp$SchedPrios)
            if (nrow(tmp) == 0) {
                next
                print("skiped workload")
            }

            i <- i+1
            plotTitle = sprintf("Workload: %s                                 ",
                workload)

            yLab = 'TailStretch (Log Scale)\n'
            xLab <- 'Message Sizes (Cumulative Sizes %)'

            # You might ask why I'm using "x=SizeCumPercent-SizeCntPercent/200"
            # in the plot? The reason is that ggplot geom_bar is so dumb and I
            # was not able to shift the bars to the write while setting the
            # width of each bar to be equal to it's size probability. So I
            # ended up manaully shift the bars to the the left for half of the
            # probability and setting the width equal to the probability
            tailStretchPlot[[i]] <- ggplot() + geom_step(data=tmp,
                aes(x=SizeCumPercent-SizeCntPercent/2, y=TailStretch,
                width=SizeCntPercent, colour=SchedPrios), size=3)

            plotTitle <- paste(append(unlist(strsplit(plotTitle, split='')),
                '\n', as.integer(nchar(plotTitle)/2)), sep='', collapse='')

            xIntervals <- findInterval(c(0)+seq(2,102,10),
                tmp[tmp$SchedPrios==unique(tmp$SchedPrios)[1],]$SizeCumPercent)

            tailStretchPlot[[i]] <- tailStretchPlot[[i]] +
                theme(text = element_text(size=1.5*textSize),
                    axis.text = element_text(size=1.3*textSize),
                    axis.text.x = element_text(angle=75, vjust=0.5),
                    strip.text = element_text(size = textSize),
                    plot.title = element_text(size = 1.2*titleSize,
                    color='darkblue'), plot.margin=unit(c(2,2,2.5,2.2),"cm"),
                    legend.position = c(0.1, 0.85),
                    legend.text = element_text(size=1.5*textSize)) +
                guides(colour = guide_legend(
                    override.aes = list(size=textSize/4)))+
                scale_x_continuous(limits = c(0,101),
                    breaks = tmp[xIntervals,]$SizeCumPercent,
                    labels=tmp[xIntervals,]$MsgSizeRange, expand = c(0, 0)) +
                scale_y_log10(breaks=c(1,2,3,4,5,10,15)) +
                coord_cartesian(ylim=c(1, yLimit)) +
                labs(title = plotTitle, y = yLab, x = xLab)
        }

    }
    pdf(sprintf(paste("plots/schedVsUnschedPrio/",
        "TailStretchVsSchedUnschedPrios_rho%s_SizePct.pdf", sep=''), rho),
        width=30*length(prioLevels),
        height=20*length(workloads))
    args.list <- c(tailStretchPlot, list(ncol=length(prioLevels)))
    do.call(grid.arrange, args.list)
    dev.off()
}

rttIntervals = c(0, .155, 1, 2, 3, 5, 10, 1e6)*9326
for (rho in rhos) {
    i <- 0
    tailStretchPlot = list()
    for (prioLevel in prioLevels) {
        for (workload in workloads) {
            # Use CDF as the x axis
            tmp <- subset(tailStretchVsSize, WorkLoad==workload &
                PrioLevels==prioLevel & LoadFactor==rho,
                select=c('MsgSizeRange', 'SizeCntPercent', 'SchedPrios',
                'SizeCumPercent', 'TailStretch'))
            tmp$SchedPrios <- factor(tmp$SchedPrios)
            if (nrow(tmp) == 0) {
                next
                print("skiped workload")
            }

            i <- i+1
            plotTitle = sprintf("Workload: %s                                 ",
                workload)

            yLab = 'TailStretch (Log Scale)\n'
            xLab <- 'Message Sizes (Log Scale RTT)'

            tailStretchPlot[[i]] <- ggplot() + geom_step(data=tmp,
                aes(x=MsgSizeRange, y=TailStretch, colour=SchedPrios), size=2)

            plotTitle <- paste(append(unlist(strsplit(plotTitle, split='')),
                '\n', as.integer(nchar(plotTitle)/2)), sep='', collapse='')

            xIntervals <- findInterval(rttIntervals,
                tmp[tmp$SchedPrios==unique(tmp$SchedPrios)[1],]$MsgSizeRange)

            tailStretchPlot[[i]] <- tailStretchPlot[[i]] +
                theme(text = element_text(size=1.5*textSize),
                    axis.text = element_text(size=1.3*textSize),
                    axis.text.x = element_text(angle=75, vjust=0.5),
                    strip.text = element_text(size = textSize),
                    plot.title = element_text(size = 1.2*titleSize,
                    color='darkblue'), plot.margin=unit(c(2,2,2.5,2.2),"cm"),
                    legend.position = c(0.1, 0.85),
                    legend.text = element_text(size=1.5*textSize)) +
                guides(colour = guide_legend(
                    override.aes = list(size=textSize/4)))+
                scale_x_log10(
                    breaks = tmp[xIntervals,]$MsgSizeRange,
                    labels=tmp[xIntervals,]$MsgSizeRange, expand = c(0, 0)) +
                scale_y_log10(breaks=c(1,2,3,4,5,10,15)) +
                coord_cartesian(ylim=c(1, yLimit)) +
                labs(title = plotTitle, y = yLab, x = xLab)
        }

    }
    pdf(sprintf(paste("plots/schedVsUnschedPrio/",
        "TailStretchVsSchedUnschedPrios_rho%s_xSize.pdf", sep=''), rho),
        width=30*length(prioLevels),
        height=20*length(workloads))
    args.list <- c(tailStretchPlot, list(ncol=length(prioLevels)))
    do.call(grid.arrange, args.list)
    dev.off()
}



for (rho in rhos) {
    i <- 0
    tailStretchPlot = list()
    for (prioLevel in prioLevels) {
        for (workload in workloads) {
            # Use CDF as the x axis
            tmp <- subset(tailStretchVsSize, WorkLoad==workload &
                PrioLevels==prioLevel & LoadFactor==rho,
                select=c('MsgSizeRange', 'BytesPercent', 'SchedPrios',
                'BytesCumPercent', 'TailStretch'))
            tmp$SchedPrios <- factor(tmp$SchedPrios)
            if (nrow(tmp) == 0) {
                next
                print("skiped workload")
            }

            i <- i+1
            plotTitle = sprintf("Workload: %s                                 ",
                workload)

            yLab = 'TailStretch (Log Scale)\n'
            xLab <- 'Message Sizes (Cumulative Bytes %)'

            # You might ask why I'm using "x=SizeCumPercent-SizeCntPercent/200"
            # in the plot? The reason is that ggplot geom_bar is so dumb and I
            # was not able to shift the bars to the write while setting the
            # width of each bar to be equal to it's size probability. So I
            # ended up manaully shift the bars to the the left for half of the
            # probability and setting the width equal to the probability
            tailStretchPlot[[i]] <- ggplot() + geom_step(data=tmp,
                aes(x=BytesCumPercent-BytesPercent/2, y=TailStretch,
                width=BytesPercent, colour=SchedPrios), size=3)

            plotTitle <- paste(append(unlist(strsplit(plotTitle, split='')),
                '\n', as.integer(nchar(plotTitle)/2)), sep='', collapse='')

            xIntervals <- findInterval(c(0)+seq(2,102,10),
                tmp[tmp$SchedPrios==unique(tmp$SchedPrios)[1],]$BytesCumPercent)

            tailStretchPlot[[i]] <- tailStretchPlot[[i]] +
                theme(text = element_text(size=1.5*textSize),
                    axis.text = element_text(size=1.3*textSize),
                    axis.text.x = element_text(angle=75, vjust=0.5),
                    strip.text = element_text(size = textSize),
                    plot.title = element_text(size = 1.2*titleSize,
                    color='darkblue'), plot.margin=unit(c(2,2,2.5,2.2),"cm"),
                    legend.position = c(0.1, 0.85),
                    legend.text = element_text(size=1.5*textSize)) +
                guides(colour = guide_legend(
                    override.aes = list(size=textSize/4)))+
                scale_x_continuous(limits = c(0,101),
                    breaks = tmp[xIntervals,]$BytesCumPercent,
                    labels=tmp[xIntervals,]$MsgSizeRange, expand = c(0, 0)) +
                scale_y_log10(breaks=c(1,2,3,4,5,10,15)) +
                coord_cartesian(ylim=c(1, yLimit)) +
                labs(title = plotTitle, y = yLab, x = xLab)
        }

    }
    pdf(sprintf(paste("plots/schedVsUnschedPrio/",
        "TailStretchVsSchedUnschedPrios_rho%s_BytesPct.pdf", sep=''), rho),
        width=30*length(prioLevels),
        height=20*length(workloads))

    args.list <- c(tailStretchPlot, list(ncol=length(prioLevels)))
    do.call(grid.arrange, args.list)
    dev.off()
}



