#!/usr/bin/Rscript
library(reshape2)
library(ggplot2)
library(gridExtra)
library(plyr)

# Plots the stretch vs. unsched bytes from text data files generated by
# PlotDigeter.py script
wastedBw <- read.table("wastedBw.txt", na.strings = "NA",
    col.names=c('transport', 'workload', 'prioLevels', 'redundancyFactor',
    'loadFactor', 'nominalLoadFactor', 'wastedBw', 'activeWastedBw',
    'totalWastedOversubBw', 'oversubWastedOversubBw'), header=TRUE)

wastedBw$redundancyFactor <- factor(wastedBw$redundancyFactor)
i <- 0
plotList <- list()
textSize = 13
yLab = 'Receiver Wasted Bandwidth(%)'
xLab = 'Average Load Factor(%)'
workloads <- c('FACEBOOK_KEY_VALUE', 'GOOGLE_SEARCH_RPC',
    'FABRICATED_HEAVY_MIDDLE', 'GOOGLE_ALL_RPC','FACEBOOK_HADOOP_ALL')
workloads <- workloads[workloads %in% unique(wastedBw$workload)]

yLimit = ceiling(max(wastedBw$wastedBw) / 10)*10
yLimit = 50

for (workload in workloads) {
    i <- i+1
    plotTitle = sprintf("Workload: %s", workload)
    plotList[[i]] <- ggplot(wastedBw[wastedBw$workload==workload,]) +
        geom_line(aes(x=loadFactor, y=wastedBw, colour=redundancyFactor),
            size = 1.5, alpha = 2/3) +
        geom_line(aes(x=loadFactor, y=totalWastedOversubBw,
            colour=redundancyFactor), size = 1.5, alpha = 2/3) +
        geom_line(data=data.frame(loadFactor=0:100, wastedBw=100:0),
            aes(x=loadFactor, y=wastedBw),
            color='magenta', size = 1, alpha = 2/3) +
        theme(text = element_text(size=textSize, face="bold"),
            legend.position="top", strip.text.x = element_text(size = textSize),
            strip.text.y = element_text(size = textSize),
            plot.title = element_text(size = textSize),
            panel.background = element_rect(fill = "white")) +
        coord_cartesian(ylim=c(0,yLimit), xlim=c(0,100)) +
        labs(title = plotTitle, x = xLab, y = yLab)
}

pdf("plots/wastedBw/wastedBW.pdf", width=15, height=4)
args.list <- c(plotList, list(ncol=3))
do.call(grid.arrange, args.list)
dev.off()
