#!/usr/bin/Rscript
library(reshape2)
library(ggplot2)
library(gridExtra)
library(plyr)

# Plots the stretch vs. unsched bytes from text data files generated by PlotDigeter.py script
stretchVsSize <- read.table("stretchVsUnsched.txt", na.strings = "NA",
    col.names=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent',
        'UnschedBytes', 'MeanStretch', 'MedianStretch', 'TailStretch'),
    header=TRUE)
stretchVsSize$LoadFactor <- factor(stretchVsSize$LoadFactor)

avgStretchVsSize <- subset(stretchVsSize,
    !is.na(MeanStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
    select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'UnschedBytes', 'MeanStretch'))
avgStretchVsSize <- ddply(avgStretchVsSize, .(LoadFactor, WorkLoad, UnschedBytes), transform, SizeCumPercent = round(cumsum(SizeCntPercent), 2))
avgStretchVsSize$MsgSizeRange <- as.numeric(as.character(avgStretchVsSize$MsgSizeRange))

medianStretchVsSize <- subset(stretchVsSize,
    !is.na(MedianStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
    select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'UnschedBytes', 'MedianStretch'))
medianStretchVsSize <- ddply(medianStretchVsSize, .(LoadFactor, WorkLoad, UnschedBytes), transform, SizeCumPercent = round(cumsum(SizeCntPercent), 2))
medianStretchVsSize$MsgSizeRange <- as.numeric(as.character(medianStretchVsSize$MsgSizeRange))

tailStretchVsSize <- subset(stretchVsSize,
    !is.na(TailStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
    select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'UnschedBytes', 'TailStretch'))
tailStretchVsSize <- ddply(tailStretchVsSize, .(LoadFactor, WorkLoad, UnschedBytes), transform, SizeCumPercent = round(cumsum(SizeCntPercent), 2))
tailStretchVsSize$MsgSizeRange <- as.numeric(as.character(tailStretchVsSize$MsgSizeRange))

textSize = 35
for (unsched in unique(stretchVsSize$UnschedBytes)) {
    avgStretchPlot = list()
    i <- 0
    for (workload in levels(avgStretchVsSize$WorkLoad)) {
        for (rho in unique(avgStretchVsSize$LoadFactor)) {
            i <- i+1
            tmp <- subset(avgStretchVsSize, WorkLoad==workload & LoadFactor==rho & UnschedBytes==unsched, 
                select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'SizeCumPercent', 'UnschedBytes', 'MeanStretch'))

            # You might ask why I'm using "x=SizeCumPercent-SizeCntPercent/200" in the plot. The reason is that ggplot geom_bar is so 
            # dumb and I was not able to shift the bars to the write while setting the width of each bar to be equal to it's size
            # probability. So I ended up manaully shift the bars to the the left for half of the probability and setting the width
            # equal to the probability
            avgStretchPlot[[i]] <- ggplot(tmp, aes(x=SizeCumPercent-SizeCntPercent/2, y=MeanStretch, width=SizeCntPercent)) + 
                geom_bar(stat="identity", position="identity", fill="white", color="darkgreen") +
                geom_text(data=tmp, aes(x=SizeCumPercent, y=MeanStretch/2, label=MsgSizeRange), angle=90, size=10) +
                theme(text = element_text(size=textSize, face="bold"),
                    axis.text.x = element_text(angle=75, vjust=0.5),
                    strip.text.x = element_text(size = textSize), strip.text.y = element_text(size = textSize)) +
                scale_x_continuous(breaks = tmp$SizeCumPercent) +
                labs(title = sprintf("MeanStrech VS. Cummulative Msg Size Percent, loadfactor:%s, workload:%s, unsched:%d", rho, workload, unsched),
                    x = "Cumulative Msg Size Percent")
        }
    }
    pdf(sprintf("MeanStretchVsSize_Unsched%dB.pdf", unsched), width=150, height=50)
    do.call(grid.arrange, avgStretchPlot)
    dev.off()

    medianStretchPlot = list()
    i <- 0
    for (workload in levels(medianStretchVsSize$WorkLoad)) {
        for (rho in unique(medianStretchVsSize$LoadFactor)) {
            i <- i+1
            tmp <- subset(medianStretchVsSize, WorkLoad==workload & LoadFactor==rho & UnschedBytes==unsched, 
                select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'SizeCumPercent', 'UnschedBytes', 'MedianStretch'))

            # You might ask why I'm using "x=SizeCumPercent-SizeCntPercent/200" in the plot. The reason is that ggplot geom_bar is so 
            # dumb and I was not able to shift the bars to the write while setting the width of each bar to be equal to it's size
            # probability. So I ended up manaully shift the bars to the the left for half of the probability and setting the width
            # equal to the probability
            medianStretchPlot[[i]] <- ggplot(tmp, aes(x=SizeCumPercent-SizeCntPercent/2, y=MedianStretch, width=SizeCntPercent)) + 
                geom_bar(stat="identity", position="identity", fill="white", color="darkgreen") +
                geom_text(data=tmp, aes(x=SizeCumPercent, y=MedianStretch/2, label=MsgSizeRange), angle=90, size=10) +
                theme(text = element_text(size=textSize, face="bold"),
                    axis.text.x = element_text(angle=75, vjust=0.5),
                    strip.text.x = element_text(size = textSize), strip.text.y = element_text(size = textSize)) +
                scale_x_continuous(breaks = tmp$SizeCumPercent) +
                labs(title = sprintf("MedianStrech VS. Cummulative Msg Size Percent, loadfactor:%s, workload:%s, unsched:%d", rho, workload, unsched),
                    x = "Cumulative Msg Size Percent")
        }
    }
    pdf(sprintf("MedianStretchVsSize_Unsched%dB.pdf", unsched), width=150, height=50)
    do.call(grid.arrange, medianStretchPlot)
    dev.off()

    tailStretchPlot = list()
    i <- 0
    for (workload in levels(tailStretchVsSize$WorkLoad)) {
        for (rho in unique(tailStretchVsSize$LoadFactor)) {
            i <- i+1
            tmp <- subset(tailStretchVsSize, WorkLoad==workload & LoadFactor==rho & UnschedBytes==unsched, 
                select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent', 'SizeCumPercent', 'UnschedBytes', 'TailStretch'))

            # You might ask why I'm using "x=SizeCumPercent-SizeCntPercent/200" in the plot. The reason is that ggplot geom_bar is so 
            # dumb and I was not able to shift the bars to the write while setting the width of each bar to be equal to it's size
            # probability. So I ended up manaully shift the bars to the the left for half of the probability and setting the width
            # equal to the probability
            tailStretchPlot[[i]] <- ggplot(tmp, aes(x=SizeCumPercent-SizeCntPercent/2, y=TailStretch, width=SizeCntPercent)) + 
                geom_bar(stat="identity", position="identity", fill="white", color="darkgreen") +
                geom_text(data=tmp, aes(x=SizeCumPercent, y=TailStretch/2, label=MsgSizeRange), angle=90, size=10) +
                theme(text = element_text(size=textSize, face="bold"),
                    axis.text.x = element_text(angle=75, vjust=0.5),
                    strip.text.x = element_text(size = textSize), strip.text.y = element_text(size = textSize)) +
                scale_x_continuous(breaks = tmp$SizeCumPercent) +
                labs(title = sprintf("TailStrech VS. Cummulative Msg Size Percent, loadfactor:%s, workload:%s, unsched:%d", rho, workload, unsched),
                    x = "Cumulative Msg Size Percent")
        }
    }
    pdf(sprintf("TailStretchVsSize_Unsched%dB.pdf", unsched), width=150, height=50)
    do.call(grid.arrange, tailStretchPlot)
    dev.off()
}

