#!/bin/sh

./PlotToolbox.r  cdf QueueWaitTimesInHosts  /home/behnamm/Research/RpcTransportDesign/OMNeT++Simulation/homatransport/src/dcntopo/results/QueueWaitTimes RecordAllStats-0-HostQueueWaitTime.csv 0.2  RecordAllStats-1-HostQueueWaitTime.csv 0.4  RecordAllStats-2-HostQueueWaitTime.csv 0.8
./PlotToolbox.r  cdf QueueWaitTimesInAggRouters /home/behnamm/Research/RpcTransportDesign/OMNeT++Simulation/homatransport/src/dcntopo/results/QueueWaitTimes RecordAllStats-0-AggRouterQueueWaitTime.csv 0.2  RecordAllStats-1-AggRouterQueueWaitTime.csv 0.4  RecordAllStats-2-AggRouterQueueWaitTime.csv 0.8
./PlotToolbox.r  cdf QueueWaitTimesInTorsDownward /home/behnamm/Research/RpcTransportDesign/OMNeT++Simulation/homatransport/src/dcntopo/results/QueueWaitTimes RecordAllStats-0-TorDownwardQueueWaitTime.csv 0.2  RecordAllStats-1-TorDownwardQueueWaitTime.csv 0.4  RecordAllStats-2-TorDownwardQueueWaitTime.csv 0.8
./PlotToolbox.r  cdf QueueWaitTimesInTorsUpward /home/behnamm/Research/RpcTransportDesign/OMNeT++Simulation/homatransport/src/dcntopo/results/QueueWaitTimes RecordAllStats-0-TorUpwardQueueWaitTime.csv 0.2  RecordAllStats-1-TorUpwardQueueWaitTime.csv 0.4  RecordAllStats-2-TorUpwardQueueWaitTime.csv 0.8

./PlotToolbox.r  cdf PktArrivalTimesAtHostQueue  /home/behnamm/Research/RpcTransportDesign/OMNeT++Simulation/homatransport/src/dcntopo/results/PktInterArrivalTime RecordAllStats-0-HostQueuePktArrivalTimes.csv 0.2  RecordAllStats-1-HostQueuePktArrivalTimes.csv 0.4  RecordAllStats-2-HostQueuePktArrivalTimes.csv 0.8
./PlotToolbox.r  cdf PktArrivalTimesAtTorsUpwardQueue  /home/behnamm/Research/RpcTransportDesign/OMNeT++Simulation/homatransport/src/dcntopo/results/PktInterArrivalTime  RecordAllStats-0-TorUpwardQueuePktArrivalTimes.csv 0.2  RecordAllStats-1-TorUpwardQueuePktArrivalTimes.csv 0.4  RecordAllStats-2-TorUpwardQueuePktArrivalTimes.csv 0.8
./PlotToolbox.r  cdf PktArrivalTimesAtTorsDownwardQueue  /home/behnamm/Research/RpcTransportDesign/OMNeT++Simulation/homatransport/src/dcntopo/results/PktInterArrivalTime  RecordAllStats-0-TorDownwardQueuePktArrivalTimes.csv 0.2  RecordAllStats-1-TorDownwardQueuePktArrivalTimes.csv 0.4  RecordAllStats-2-TorDownwardQueuePktArrivalTimes.csv 0.8
./PlotToolbox.r  cdf PktArrivalTimesAtAggRoutersQueue  /home/behnamm/Research/RpcTransportDesign/OMNeT++Simulation/homatransport/src/dcntopo/results/PktInterArrivalTime  RecordAllStats-0-AggRouterQueuePktArrivalTimes.csv 0.2  RecordAllStats-1-AggRouterQueuePktArrivalTimes.csv 0.4  RecordAllStats-2-AggRouterQueuePktArrivalTimes.csv 0.8

./PlotToolbox.r  cdf PktDelayDistribution  /home/behnamm/Research/RpcTransportDesign/OMNeT++Simulation/homatransport/src/dcntopo/results/PktEndToEndDelay  RecordAllStats-0-HostQueuePktArrivalTimes.csv 0.2  RecordAllStats-1-HostQueuePktArrivalTimes.csv 0.4  RecordAllStats-2-HostQueuePktArrivalTimes.csv 0.8
