#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE=make

# in parent directory (homatransport), compile homa with TESTING flag set
(cd ../../; make TESTING=1 makefiles; make -j8 MODE=debug) || exit 1

echo "*******\n\n"
# make clean and complie gtest test cases
make -j8

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi
rm -rf work/obj
cp -pPR obj work/
opp_test gen $OPT -v $TESTFILES || exit 1
echo

# Output directory
PROJECT_OUTPUT_DIR=out
CONFIGNAME=gcc-debug
PROJECTRELATIVE_PATH=src
O=../../../$PROJECT_OUTPUT_DIR/$CONFIGNAME/$PROJECTRELATIVE_PATH

# Object files for HomaTransport .cc and .msg files
OBJS=\
"$O/application/MsgSizeDistributions.o "\
"$O/application/WorkloadSynthesizer.o "\
"$O/common/Lagger.o "\
"$O/common/GlobalSignalListener.o "\
"$O/common/Util.o "\
"$O/transport/HomaConfigDepot.o "\
"$O/transport/HomaPkt.o "\
"$O/transport/HomaTransport.o "\
"$O/mocks/MockUdpSocket.o "\
"$O/transport/PriorityResolver.o "\
"$O/transport/PseudoIdealPriorityTransport.o "\
"$O/transport/UnschedByteAllocator.o "\
"$O/transport/WorkloadEstimator.o "\
"$O/application/AppMessage_m.o "\
"$O/transport/HomaPkt_m.o "\
"../obj/TestMain.o "\
"../obj/UnschedByteAllocatorTest.o "\
"../obj/HomaTransportTest.o "\
"../../../../../../share/googletest/googletest/src/obj/gtest-all.o "
echo $OBJS

GTEST_DIR=../../../../../../share/googletest/googletest

(cd work; opp_makemake -f --deep -L../../../../inet/src -lINET -lm -lpthread \
-P . -I$GTEST_DIR -I$GTEST_DIR/include -I.. -I../../../src \
-I../../../../inet/src $OBJS; $MAKE -j8) || exit 1
echo
#opp_test run $OPT -v $TESTFILES || exit 1
(cd work/SetupTests;../work -u Cmdenv \
-n.:../../../../src:../../../../../inet/src:../../../../../inet/examples \
-l../../../../../inet/src/INET homaTransportConfig.ini)
echo
echo Results can be found in ./work
